import type { DrgModeType } from "./types";

export const MAX_DIGITS = 10;
export const DRG_MODES: DrgModeType[] = ["deg", "rad", "grad"];

export const ActionTypes = {
  ALL_CLEAR: "ALL_CLEAR",
  CLEAR: "CLEAR",
  CYCLE_DRG_MODE: "CYCLE_DRG_MODE",
  TOGGLE_SHIFT_STATE: "TOGGLE_SHIFT_STATE",
  UPDATE_CURRENT_OPERAND: "UPDATE_CURRENT_OPERAND",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  EVALUATE_EXPRESSION: "EVALUATE_EXPRESSION",
  INVERT_NUMBER: "INVERT_NUMBER",
  PERCENT: "PERCENT",
  SQUARE_ROOT: "SQUARE_ROOT",
  SQUARE: "SQUARE",
  LOG: "LOG",
  POWER_OF_TEN: "POWER_OF_TEN",
  NATURAL_LOG: "NATURAL_LOG",
  EXP_X: "EXP_X",
  SIN: "SIN",
  ADJUST_VOLTAGE: "ADJUST_VOLTAGE",
};
