import type { AngleUnit } from "./types";

export const MAX_DIGITS = 10;
export const ANGLE_MODES: AngleUnit[] = ["deg", "rad", "grad"];

export const ActionTypes = {
  ALL_CLEAR: "ALL_CLEAR",
  CLEAR: "CLEAR",
  CYCLE_DRG_MODE: "CYCLE_DRG_MODE",
  TOGGLE_SHIFT_STATE: "TOGGLE_SHIFT_STATE",
  UPDATE_CURRENT_OPERAND: "UPDATE_CURRENT_OPERAND",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  EVALUATE_EXPRESSION: "EVALUATE_EXPRESSION",
  INVERT_NUMBER: "INVERT_NUMBER",
  PERCENT: "PERCENT",
  EXECUTE_FUNCTION: "EXECUTE_FUNCTION",
  ADJUST_VOLTAGE: "ADJUST_VOLTAGE",
  TODO: "TODO",
};
