export const MAX_DIGITS = 9;
export const INVERT_SYMBOL = "+/-";
export const ALL_CLEAR_SYMBOL = "AC";

export const ActionTypes = {
  ALL_CLEAR: "ALL_CLEAR",
  CLEAR: "CLEAR",
  TOGGLE_SHIFT_STATE: "TOGGLE_SHIFT_STATE",
  UPDATE_CURRENT_OPERAND: "UPDATE_CURRENT_OPERAND",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  EVALUATE_EXPRESSION: "EVALUATE_EXPRESSION",
  INVERT_NUMBER: "INVERT_NUMBER",
  PERCENT: "PERCENT",
  ADJUST_VOLTAGE: "ADJUST_VOLTAGE",
};
